# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:

  - r: devel

  - r: release
    before_cache:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    after_success:
    - Rscript -e 'covr::codecov()'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true

  - r: oldrel

  - r: 3.3

  - r: 3.2

env:
  global:
    - NOT_CRAN=true
